version: '3.9'
services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.3
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data:/usr/share/elasticsearch/data
      - odfe-log:/usr/share/elasticsearch/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    expose:
      - 9200
      - 9600
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - jper_net

  store:
    build:
      context: .
      dockerfile: store.Dockerfile
    expose:
      - 5999
    ports:
      - 5999:5999
    networks:
      - jper_net

  jper-web:
    build:
      context: ../../
      dockerfile: docker-compose/deepgreen/jper.Dockerfile
    volumes:
      - ../../:/opt/jper
      - jper_etc:/etc
      - deepgreen_home:/opt/deepgreen
      - tmp_home:/tmp
      - sftpuser:/home/sftpusers
      - data_home:/data
    env_file:
      - .env
    networks:
      - jper_net
    command:
      - bash
      - "/opt/jper/docker-compose/deepgreen/jper.entrypoint.sh"
    expose:
      - 5998
    ports:
      - 5998:5998


volumes:
  odfe-data:
  odfe-log:
  deepgreen_home:
  tmp_home:
  sftpuser:
  data_home:
  jper_etc:

networks:
  jper_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-jper_net
